/**
 * Estado global compartido de la aplicación qa_milu.
 * Todos los módulos importan este objeto y lo modifican directamente.
 */
export const state = {
    allData: [],
    filteredData: [],
    tableMode: 'qa',
    currentPage: 1,
    pageSize: 50,
    paginationEnabled: true,
    MIN_PAGE_SIZE: 5,
    sortKey: 'book_page_pos',
    sortAsc: true,
    filters: {},
    groupedVisible: false,
    selectedRevisionRowKey: '',
    columnView: 'pdf',
    newPnSet: new Set(),
    miluNewData: [],
    supersededPnSet: new Set(),
    miluSupersededData: [],
    publishedMap: new Map(),
    productExportPnSet: new Set(),
    mainDataSourceLabel: 'engine_*.json',
    currentPdfDocument: null,
    currentPdfSource: '',
    currentPdfPageNumber: 0,
    currentPdfRenderTask: null,
    currentPdfRequestToken: 0,
    currentPdfSelection: null,
    currentPdfSelectionRects: [],
    currentPdfZoom: 'fit',
    rightPanelTab: 'pdf',
    qaErrorCheckDefinitions: [
        { code: 'missing_part_no', label: 'PN vacio' },
        { code: 'missing_pos', label: 'POS vacio' },
        { code: 'missing_pn_final', label: 'PN Final vacio' },
        { code: 'pn_final_not_in_pdf', label: 'PN Final no se encuentra en el PDF asignado' },
        { code: 'missing_designation_final', label: 'Designation Final vacio' },
        { code: 'designation_final_not_in_pdf', label: 'Designation Final no se encuentra en el PDF asignado' }
    ],
    activeQaErrorChecks: new Set(),
    qaChecksScopedRows: null,
};
