/**
 * Estado global compartido de la aplicación qa_milu.
 * Todos los módulos importan este objeto y lo modifican directamente.
 */
export const state = {
    allData: [],
    filteredData: [],
    currentPage: 1,
    pageSize: 50,
    MIN_PAGE_SIZE: 5,
    sortKey: 'book_page_pos',
    sortAsc: true,
    filters: {},
    groupedVisible: false,
    selectedRevisionRowKey: '',
    columnView: 'pdf',
    newPnSet: new Set(),
    miluNewData: [],
    supersededPnSet: new Set(),
    miluSupersededData: [],
    publishedMap: new Map(),
    productExportPnSet: new Set(),
    mainDataSourceLabel: 'engine_*.json',
    currentPdfDocument: null,
    currentPdfSource: '',
    currentPdfPageNumber: 0,
    currentPdfRenderTask: null,
    currentPdfRequestToken: 0,
    currentPdfSelection: null,
    currentPdfSelectionRects: [],
    rightPanelTab: 'pdf',
    qaErrorCheckDefinitions: [
        { code: 'missing_id', label: 'ID vacio' },
        { code: 'missing_part_no', label: 'PN vacio' },
        { code: 'missing_source_file', label: 'source_file vacio' },
        { code: 'missing_source_page', label: 'Source Page vacio' },
        { code: 'missing_pos', label: 'POS vacio' },
        { code: 'missing_designation_final', label: 'designation_final vacio' },
        { code: 'missing_measurement_final', label: 'measurement_final vacio' },
        { code: 'missing_weight_final', label: 'weight_final vacio' },
        { code: 'duplicate_id', label: 'ID duplicado' },
        { code: 'duplicate_logical_row', label: 'Fila logica duplicada' },
        { code: 'invalid_revision_estado', label: 'revision_estado invalido' },
        { code: 'invalid_revision_accion', label: 'revision_accion invalida' },
        { code: 'en_web_without_photo', label: 'EN_WEB sin foto' },
        { code: 'no_pn', label: 'Sin PN (dinamico)' },
        { code: 'export_inconsistency', label: 'PN en New y Superseded (dinamico)' },
        { code: 'export_mismatch_critical', label: 'Mismatch export critico (dinamico)' },
        { code: 'export_mismatch_warning', label: 'Mismatch export warning (dinamico)' }
    ],
    activeQaErrorChecks: new Set(),
};
